version: '3.7'

services:
  nginx:
    image: nginx:1.21.6
    container_name: webserver2
    restart: on-failure
    ports:
      - "8000:80"
    volumes:
     - ./www:/var/www
     - ./conf.d:/etc/nginx/conf.d
     - ./conf/nginx.conf:/etc/nginx/nginx.conf
